RECAPTCHA_PUBLIC_KEY = "6LeIxAcTAAAAAJcZVRqyHh71UMIEGNQ_MXjiZKhI"
RECAPTCHA_PRIVATE_KEY = "6LeIxAcTAAAAAGG-vFI1TnRWxMZNFuojJ4WifJWe"
SQLALCHEMY_DATABASE_URI = 'postgresql://postgres:rR0sWw9GPJ14@gambit-db.c6md0jt9jkwl.ap-northeast-2.rds.amazonaws.com:5432/postgres'
AWS_SECRET_ACCESS_KEY = 'SFUB68Bagx/zFFX5H6KWZx7XtQCY//asIYei+UyU'
